import { useMemo,useRef,useState } from "react";
import type { ReactNode } from "react";
import { CheckCircle2,Download,Eye,EyeOff,Lightbulb,LightbulbOff,Eraser,Undo2,Redo2,Trash2 } from "lucide-react";
import DrawingBoard from "./canvas/DrawingBoard";
import DrawingToolbar,{COLORS} from "./canvas/DrawingToolbar";
import type { ActionName } from "./canvas/DrawingToolbar";
import {expectedShapeToDrawable,gradeDrawing} from "./canvas/grading";
import type {ExpectedShape,GradeResult} from "./canvas/grading";
import type {BoundingBox,DrawingBoardHandle,InitialObjectSpec,ToolName,UserDrawing} from "./types";
import "./DrawingCanvas.css";
export type {BoundingBox,InitialObjectSpec,ToolName,UserDrawing,ExpectedShape,GradeResult,ActionName};export {COLORS};
export interface DrawingAppProps{questionText?:ReactNode;boundingBox?:BoundingBox;xLabel?:string;yLabel?:string;initialObjects?:InitialObjectSpec[];expectedDrawing?:ExpectedShape[];suggestedAnswer?:InitialObjectSpec[];enabledTools?:ToolName[];enabledActions?:ActionName[];defaultTool?:ToolName;defaultColor?:string;colors?:string[];showColorPicker?:boolean;showNavigation?:boolean;showGradeButton?:boolean;showSuggestedAnswerButton?:boolean;showDownloadButton?:boolean;downloadFilename?:string;showOutputButton?:boolean;width?:number|string;height?:number|string;}
function question(node:ReactNode){return typeof node!=="string"?node:node.trim().split(/\n\s*\n/).map((p,i)=><p key={i}>{p.trim()}</p>)}
export default function DrawingApp({questionText,boundingBox=[-10,10,-10,10],xLabel="x",yLabel="y",initialObjects,expectedDrawing,suggestedAnswer,enabledTools,enabledActions,defaultTool="select",defaultColor="#111827",colors,showColorPicker=true,showNavigation=false,showGradeButton=true,showSuggestedAnswerButton=true,showDownloadButton=true,downloadFilename="drawing.png",showOutputButton=true,width="100%",height=720}:DrawingAppProps){
 const [tool,setTool]=useState<ToolName>(defaultTool),[color,setColor]=useState(defaultColor),[seq,setSeq]=useState(0),[canUndo,setCanUndo]=useState(false),[canRedo,setCanRedo]=useState(false),[showData,setShowData]=useState(false),[data,setData]=useState("[]"),[grade,setGrade]=useState<GradeResult|null>(null),[showSuggested,setShowSuggested]=useState(false);const board=useRef<DrawingBoardHandle>(null);
 const refresh=()=>{const value=board.current?.getUserDrawings()??[];setData(JSON.stringify(value,null,2));return value};
 const hasExpected=!!expectedDrawing?.length,hasSuggested=!!suggestedAnswer?.length,gradeEnabled=showGradeButton&&hasExpected,suggestedEnabled=showSuggestedAnswerButton&&(hasSuggested||hasExpected),actions=enabledActions??["undo","redo","clear"],eraserEnabled=!enabledTools||enabledTools.includes("eraser"),footerEnabled=showDownloadButton||showOutputButton||gradeEnabled||suggestedEnabled||eraserEnabled||actions.length>0;
 const overlay=useMemo(()=>!showSuggested?undefined:hasSuggested?suggestedAnswer:(expectedDrawing??[]).map(x=>expectedShapeToDrawable(x,boundingBox)).filter((x):x is InitialObjectSpec=>!!x),[showSuggested,hasSuggested,suggestedAnswer,expectedDrawing,boundingBox]);
 const chooseTool=(next:ToolName)=>{setTool(next);setSeq(n=>n+1)};
 return <div className="drawing-app-root" style={{width}}>{questionText!=null&&questionText!==""&&<div className="drawing-app-question">{question(questionText)}</div>}<div className="drawing-app" style={{height}}><div className="canvas-row"><main className="board-container"><div className="board"><DrawingBoard ref={board} boundingBox={boundingBox} xLabel={xLabel} yLabel={yLabel} initialObjects={initialObjects} activeTool={tool} color={color} showNavigation={showNavigation} toolActivationSeq={seq} onHistoryChange={s=>{setCanUndo(s.canUndo);setCanRedo(s.canRedo)}} onDrawingsChange={()=>{if(showData)refresh()}} overlayObjects={overlay}/></div></main><DrawingToolbar activeTool={tool} onToolChange={chooseTool} color={color} onColorChange={setColor} enabledTools={enabledTools} colors={colors} showColorPicker={showColorPicker}/></div>
 {footerEnabled&&<footer className="drawing-app-footer"><div className="footer-actions">{eraserEnabled&&<button className={`output-button ${tool==="eraser"?"footer-tool-active":""}`} aria-pressed={tool==="eraser"} onClick={()=>chooseTool("eraser")} title="Eraser" aria-label="Eraser"><Eraser/></button>}{actions.includes("undo")&&<button className="output-button" onClick={()=>board.current?.undo()} disabled={!canUndo} title="Undo" aria-label="Undo"><Undo2/></button>}{actions.includes("redo")&&<button className="output-button" onClick={()=>board.current?.redo()} disabled={!canRedo} title="Redo" aria-label="Redo"><Redo2/></button>}{actions.includes("clear")&&<button className="output-button footer-delete-button" onClick={()=>board.current?.clear()} title="Clear board" aria-label="Clear board"><Trash2/></button>}{showDownloadButton&&<button className="output-button" onClick={()=>board.current?.downloadImage(downloadFilename)} aria-label="Download Image"><Download/></button>}{showOutputButton&&<button className="output-button" onClick={()=>{if(!showData)refresh();setShowData(v=>!v)}} aria-label={showData?"Hide Drawing Data":"Show Drawing Data"}>{showData?<EyeOff/>:<Eye/>}</button>}{gradeEnabled&&<button className="grade-button" onClick={()=>setGrade(gradeDrawing(expectedDrawing??[],refresh(),boundingBox))}><CheckCircle2/>Grade</button>}{suggestedEnabled&&<button className="grade-button suggested-button" aria-pressed={showSuggested} onClick={()=>setShowSuggested(v=>!v)}>{showSuggested?<LightbulbOff/>:<Lightbulb/>}{showSuggested?"Hide Feedback":"Feedback"}</button>}</div>{showData&&<pre className="output-panel">{data}</pre>}{grade&&<div className="grade-result"><b>Score: {grade.correct} / {grade.total} ({grade.score}%)</b><ul>{grade.details.map(x=><li key={x.index} className={x.correct?"grade-correct":"grade-incorrect"}>Shape {x.index+1} ({x.tool}): {x.correct?"Correct":"Incorrect"} — {x.reason}</li>)}</ul></div>}</footer>}</div></div>;
}
